version: '3'

services:

  web:

    container_name: ss_web
    build: ./web

    environment:
      - APACHE_RUN_USER=www-data
    volumes:
      - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
    ports:
      # - 8080:80
      - 8080:80
    working_dir: ${APP_PATH_CONTAINER}

  db:

    image: mariadb
    container_name: ss_db

    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ${DB_PATH_HOST}:/var/lib/mysql
    ports:
      - 3306:3306
  adminer:

    image: adminer
    container_name: ss_adminer

    restart: always
    ports:
      - 6080:8080

    working_dir: ${APP_PATH_CONTAINER}

  # composer:

  #   image: composer:1.4
  #   container_name: ss_composer

  #   volumes:
  #     - ${APP_PATH_HOST}:${APP_PATH_CONTAINER}
  #   working_dir: ${APP_PATH_CONTAINER}
  #   # command: 
  #     # -  composer install